return {
  kinds = {
    Array = " ",
    Boolean = " ",
    Class = " ",
    Color = " ",
    Constant = " ",
    Constructor = " ",
    Copilot = " ",
    Enum = " ",
    EnumMember = " ",
    Event = " ",
    Field = " ",
    File = " ",
    Folder = " ",
    Function = " ",
    Interface = " ",
    Key = " ",
    Keyword = " ",
    Method = " ",
    Module = " ",
    Namespace = " ",
    Null = " ",
    Number = " ",
    Object = " ",
    Operator = " ",
    Package = " ",
    Property = " ",
    Reference = " ",
    Snippet = " ",
    String = " ",
    Struct = " ",
    Text = " ",
    TypeParameter = " ",
    Unit = " ",
    Value = " ",
    Variable = " ",
  },
  ui = {
    BookMark = "",
    Bug = "",
    Calendar = "",
    Check = "",
    ChevronRight = ">",
    Circle = "",
    Close = "",
    Code = "",
    Comment = "",
    Dashboard = "",
    Fire = "",
    Gear = "",
    History = "",
    Lightbulb = "",
    List = "",
    Lock = "",
    NewFile = "",
    Note = "",
    Package = "",
    Pencil = "",
    Project = "",
    Search = "",
    SignIn = "",
    Tab = "",
    Table = "",
    Telescope = "",
  },
  diagnostics = {
    Error = " ",
    Hint = "",
    Information = "",
    Question = "",
    Warning = "",
  },
  lsp = {
    server_installed = "✓",
    server_pending = "➜",
    server_uninstalled = "✗",
  },
  git = {
    Add = "",
    Branch = "",
    Diff = "",
    Ignore = "◌",
    Mod = "",
    Octoface = "",
    Remove = "",
    Rename = "➜",
    Repo = "",
    Staged = "S",
    Unmerged = "",
    Unstaged = "",
    Untracked = "U",
  },
  winbar = {
    FileIcon = "",
  },
  clock = " ",
}
-- The line beneath this is called `modeline`. See `:help modeline`
-- vim: ts=2 sts=2 sw=2 et
